version: 2.1

defaults: &defaults
  docker:
    - image: springmt/amazon-linux2-ruby:2.7
      environment:
        RAILS_ENV: test
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: yes

jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: bundle -j4 --path=vendor/bundle
      - run:
          command: bundle exec rubocop
      - run:
          command: bundle exec rake db:create
      - run:
          command: RAILS_ENV=test bundle exec ridgepole -c config/database.yml -f db/Schemafile -E test --apply
      - run:
          command: BUNDLE_PATH=vendor/bundle BUNDLE_GEMFILE=Gemfile bundle exec rspec --format RspecJunitFormatter -o /tmp/test-results/rspec.xml --format progress

workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore:
                - gh-pages
