version: 2.1

defaults: &defaults
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-aritifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
  docker:
    - image: springmt/amazon-linux2-ruby:2.7
      environment:
        RAILS_ENV: test
    - image: circleci/mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: yes

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - ecs-rails-sample-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle -j4 --path=vendor/bundle
      - save_cache:
          key: /ecs-rails-sample-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          command: bundle exec rake db:create
      - run:
          command: RAILS_ENV=test bundle exec ridgepole -c config/database.yml -f db/Schemafile -E test --apply
      - run:
          command: BUNDLE_PATH=vendor/bundle BUNDLE_GEMFILE=Gemfile bundle exec rspec --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec.xml --format progress
      - store_test_results:
          path:  /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-aritifacts

workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore:
                - gh-pages
